### ISSUE TITLE
_IncompatibleKeys

### ISSUE THREAD

**Issue by pythoncoder96** [TimothyHTimothy/FAST-VQA#39]
This is yml file
```
name: FAST-VQA-B-Refactor-1*4
num_epochs: 1
l_num_epochs: 0
warmup_epochs: 2.5
ema: true
save_model: true
batch_size: 4
num_workers: 6

wandb:
    project_name: VQA_Experiments_2022

data:
    train:
        type: FusionDataset
        args:
            phase: train
            anno_file: ./examplar_data_labels/dataset/train_list.txt
            data_prefix: ../output_videos/
            sample_types:
                fragments:
                    fragments_h: 7
                    fragments_w: 7
                    fsize_h: 32
                    fsize_w: 32
                    aligned: 32
                    clip_len: 32
                    frame_interval: 2
                    num_clips: 1
    
    val-ltest:
        type: FusionDataset
        args:
            phase: test
            anno_file: ./examplar_data_labels/dataset/val_list.txt
            data_prefix: ../output_videos/
            sample_types:
                #resize:
                #    size_h: 224
                #    size_w: 224
                fragments:
                    fragments_h: 7
                    fragments_w: 7
                    fsize_h: 32
                    fsize_w: 32
                    aligned: 32
                    clip_len: 32
                    frame_interval: 2
                    num_clips: 4 
    
model:
    type: DiViDeAddEvaluator
    args:
        backbone:
            fragments:
                checkpoint: false
                pretrained: 
        backbone_size: swin_tiny_grpb
        backbone_preserve_keys: fragments
        divide_head: false
        vqa_head:
            in_channels: 768
            hidden_channels: 64
            
optimizer:
    lr: !!float 1e-3
    backbone_lr_mult: !!float 1e-1
    wd: 0.05
        
load_path: ../swin_tiny_patch244_window877_kinetics400_1k.pth
```
I am unable to load pre-trained swin model. 
Got an error like this
```
_IncompatibleKeys(missing_keys=['fragments_backbone.layers.0.blocks.0.attn.fragment_position_bias_table', 'fragments_backbone.layers.0.blocks.1.attn.fragment_position_bias_table
```
